### ISSUE TITLE
Can't install the package using pip.

### ISSUE THREAD

**Issue by kazemSafari** [patrickzib/motiflets#2]
```UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1113: character maps to <undefined>```

```
Collecting motiflets
  Using cached motiflets-0.4.2.tar.gz (77.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [19 lines of output]
      Traceback (most recent call last):
        File "....\miniconda3\envs\motifs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "...\miniconda3\envs\motifs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "...\miniconda3\envs\motifs\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "...\AppData\Local\Temp\pip-build-env-y_azuz2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "...\AppData\Local\Temp\pip-build-env-y_azuz2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "...\AppData\Local\Temp\pip-build-env-y_azuz2x\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
        File "...\miniconda3\envs\motifs\lib\pathlib.py", line 1267, in read_text
          return f.read()
        File "...\miniconda3\envs\motifs\lib\encodings\cp1252.py", line 23, in decode
          return codecs.charmap_decode(input,self.errors,decoding_table)[0]
      UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 1113: character maps to <undefined>
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by patrickzib** [comment]
Thank you very much for reporting this issue. I have never seen this. Can you provide some more detail? I.e. what system you are running?

Nonetheless, I have pushed an update.

`pip install motiflets==0.4.3`

Can you try this?

**Comment by kazemSafari** [comment]
Thank you so much for your quick reply. I tried and installed it on a separate virtual env using the above command and it worked. So thank you. I really appreciate it.

**Comment by patrickzib** [comment]
Glad to hear, it did solve the problem. Thank you for reporting the issue!
